### ISSUE TITLE
Questions about the port forwarding 

### ISSUE THREAD

**Issue by xslittlegrass** [sakra/Tunnel#1]
Hi Sakra,

Thanks for sharing Tunnel, it helped me a lot!

I have a question about the SSH port forwarding used in Tunnel. In the Tunnel, the ssh server is the same machine that the remote kernel is running on. Is it possible to use a different machine as the SSH server? For example, the front end is running on my local machine A, and the kernel is running at B behind a firewall. And Tunnel applies in this situation. Consider if the kernel is required to run on a different machine C, and B and C have unblocked TCP/IP access between them. Is it possible to create a tunnel between A and C through B, so that the remote kernel runs on C? Thanks

**Comment by sakra** [comment]
This is doable by using machine B as an SSH jump host to get to machine C. You are logging in to machine B from from A and then B is instructed to forward all SSH traffic to machine C.

The following prerequisites apply:
- The involved machines use OpenSSH and run Linux or OS X. I don't think this works with Windows.
- OpenSSH server must be running on host B and C.
- On machine A you have to set up a `ProxyCommand` host configuration for getting to machine C in `~/.ssh/config`, e.g. named `C_through_B`.
- The host `C_through_B` can then be used as the remote machine name with the Tunnel package.

See https://wiki.gentoo.org/wiki/SSH_jump_host for more information.

**Comment by xslittlegrass** [comment]
Thank you very much, that solves my problem.
