### ISSUE TITLE
Dynamics are not working

### ISSUE THREAD

**Issue by msollami** [sakra/Tunnel#3]
I realize 11.1 is not officially supported.  However, I followed your instructions exactly and everything works. All except for Dynamic behavior as this screenshot shows:

![image](https://cloud.githubusercontent.com/assets/1467556/25544829/52521e44-2c2a-11e7-9ec1-67f3bb37a310.png)

Is there anything I can do to get around it?

**Comment by sakra** [comment]
Dynamic behavior does not work for version 11.1. In order for dynamic behavior to work, the service and preemptive link between the kernel and the front end need to be forwarded over SSH, which is not longer doable for Tunnel with version 11.1.

**Comment by xslittlegrass** [comment]
@sakra Could you comment a little more on the changes in version 11.1 that prevent forwarding the service and preemptive links?

**Comment by sakra** [comment]
The parallel links (aka service and preemptive links) are now setup differently between the kernel and the front end. The new method is undocumented, the only hint I found is a comment in the JLink source code file `LinkSnooper.java`:

          // This is the new method of establishing parallel links, available in v11.1+ of the FrontEnd

Looking at the code, it seems that the parallel links are now established in the same way as the main link, i.e., as a callback connection from the kernel to the front end. The creation of the listening link side of the parallel links is now hard-coded in the front end. For the Tunnel scripts there is no way to obtain the information about the parallel links which would be necessary to forward the corresponding TCP/IP ports upon connecting to the remote machine.
